import { DroneCameraProfile, FlightConfig } from '../types';

export const DRONE_PROFILES: DroneCameraProfile[] = [
  {
    id: 'dji-mini-4-pro',
    name: 'DJI Mini 4 Pro / Mini 3 Pro (48MP Mode)',
    manufacturer: 'DJI',
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    imageWidthPx: 8064,
    imageHeightPx: 6048,
    focalLengthMm: 6.72,
    maxFlightTimeMin: 34,
    safeFlightTimeMin: 23,
    defaultSpeedMs: 6.5,
    maxSpeedMs: 16.0,
    hasMechanicalShutter: false,
    notes: 'Sensor 1/1.3" CMOS, lente 24mm equivalente f/1.7'
  },
  {
    id: 'dji-mini-3-12mp',
    name: 'DJI Mini 3 / Mini 4 Pro (12MP Padrão)',
    manufacturer: 'DJI',
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    imageWidthPx: 4032,
    imageHeightPx: 3024,
    focalLengthMm: 6.72,
    maxFlightTimeMin: 38,
    safeFlightTimeMin: 25,
    defaultSpeedMs: 6.0,
    maxSpeedMs: 16.0,
    hasMechanicalShutter: false,
    notes: 'Sensor 1/1.3" CMOS, excelente sensibilidade à luz'
  },
  {
    id: 'dji-mini-2',
    name: 'DJI Mini 2 / SE / 2 SE / Lito X1',
    manufacturer: 'DJI',
    sensorWidthMm: 6.17,
    sensorHeightMm: 4.55,
    imageWidthPx: 4000,
    imageHeightPx: 3000,
    focalLengthMm: 4.49,
    maxFlightTimeMin: 31,
    safeFlightTimeMin: 20,
    defaultSpeedMs: 5.5,
    maxSpeedMs: 16.0,
    hasMechanicalShutter: false,
    notes: 'Sensor 1/2.3" CMOS, 12MP, 24mm eq'
  },
  {
    id: 'dji-air-3-wide',
    name: 'DJI Air 3 (Câmera Grande Angular 24mm)',
    manufacturer: 'DJI',
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    imageWidthPx: 8064,
    imageHeightPx: 6048,
    focalLengthMm: 6.72,
    maxFlightTimeMin: 46,
    safeFlightTimeMin: 30,
    defaultSpeedMs: 8.0,
    maxSpeedMs: 21.0,
    hasMechanicalShutter: false,
    notes: 'Sensor duplo 1/1.3" CMOS 48MP'
  },
  {
    id: 'dji-air-2s',
    name: 'DJI Air 2S',
    manufacturer: 'DJI',
    sensorWidthMm: 13.2,
    sensorHeightMm: 8.8,
    imageWidthPx: 5472,
    imageHeightPx: 3648,
    focalLengthMm: 8.38,
    maxFlightTimeMin: 31,
    safeFlightTimeMin: 21,
    defaultSpeedMs: 7.0,
    maxSpeedMs: 19.0,
    hasMechanicalShutter: false,
    notes: 'Sensor 1" CMOS 20MP, 22mm eq'
  },
  {
    id: 'dji-mavic-3-enterprise',
    name: 'DJI Mavic 3 Enterprise (M3E - Obturador Mecânico)',
    manufacturer: 'DJI',
    sensorWidthMm: 17.3,
    sensorHeightMm: 13.0,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    focalLengthMm: 12.29,
    maxFlightTimeMin: 45,
    safeFlightTimeMin: 32,
    defaultSpeedMs: 12.0,
    maxSpeedMs: 21.0,
    hasMechanicalShutter: true,
    notes: 'Padrão ouro em aerofotogrametria, sensor 4/3 20MP com obturador mecânico'
  },
  {
    id: 'dji-mavic-3-classic',
    name: 'DJI Mavic 3 / Mavic 3 Pro / Classic',
    manufacturer: 'DJI',
    sensorWidthMm: 17.3,
    sensorHeightMm: 13.0,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    focalLengthMm: 12.29,
    maxFlightTimeMin: 43,
    safeFlightTimeMin: 30,
    defaultSpeedMs: 8.5,
    maxSpeedMs: 21.0,
    hasMechanicalShutter: false,
    notes: 'Sensor Hasselblad 4/3 CMOS 20MP'
  },
  {
    id: 'dji-mavic-3-multispectral',
    name: 'DJI Mavic 3 Multispectral (M3M)',
    manufacturer: 'DJI',
    sensorWidthMm: 17.3,
    sensorHeightMm: 13.0,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    focalLengthMm: 12.29,
    maxFlightTimeMin: 43,
    safeFlightTimeMin: 30,
    defaultSpeedMs: 10.0,
    maxSpeedMs: 21.0,
    hasMechanicalShutter: true,
    notes: 'RGB 20MP + 4 bandas multiespectrais (Green, Red, RedEdge, NIR)'
  },
  {
    id: 'dji-phantom-4-pro-rtk',
    name: 'DJI Phantom 4 Pro V2.0 / RTK',
    manufacturer: 'DJI',
    sensorWidthMm: 13.2,
    sensorHeightMm: 8.8,
    imageWidthPx: 5472,
    imageHeightPx: 3648,
    focalLengthMm: 8.8,
    maxFlightTimeMin: 30,
    safeFlightTimeMin: 20,
    defaultSpeedMs: 7.5,
    maxSpeedMs: 20.0,
    hasMechanicalShutter: true,
    notes: 'Sensor 1" CMOS 20MP com obturador mecânico'
  },
  {
    id: 'dji-matrice-350-p1-35mm',
    name: 'DJI Matrice 350 RTK + Zenmuse P1 (Lente 35mm)',
    manufacturer: 'DJI',
    sensorWidthMm: 35.9,
    sensorHeightMm: 24.0,
    imageWidthPx: 8192,
    imageHeightPx: 5460,
    focalLengthMm: 35.0,
    maxFlightTimeMin: 55,
    safeFlightTimeMin: 38,
    defaultSpeedMs: 14.0,
    maxSpeedMs: 23.0,
    hasMechanicalShutter: true,
    notes: 'Full-frame 45MP, precisão cartográfica milimétrica'
  },
  {
    id: 'autel-evo-ii-pro',
    name: 'Autel EVO II Pro 6K',
    manufacturer: 'Autel',
    sensorWidthMm: 13.2,
    sensorHeightMm: 8.8,
    imageWidthPx: 5472,
    imageHeightPx: 3648,
    focalLengthMm: 10.75,
    maxFlightTimeMin: 40,
    safeFlightTimeMin: 28,
    defaultSpeedMs: 8.0,
    maxSpeedMs: 20.0,
    hasMechanicalShutter: false,
    notes: 'Sensor 1" CMOS 20MP 6K'
  },
  {
    id: 'custom-camera',
    name: 'Câmera Personalizada / Outro Drone',
    manufacturer: 'Custom',
    sensorWidthMm: 13.2,
    sensorHeightMm: 8.8,
    imageWidthPx: 5472,
    imageHeightPx: 3648,
    focalLengthMm: 8.8,
    maxFlightTimeMin: 30,
    safeFlightTimeMin: 20,
    defaultSpeedMs: 7.0,
    maxSpeedMs: 20.0,
    hasMechanicalShutter: false,
    isCustom: true,
    notes: 'Defina os parâmetros do seu sensor manualmente'
  }
];

export const DEFAULT_FLIGHT_CONFIG: FlightConfig = {
  droneId: 'dji-mini-4-pro',
  altitudeMode: 'TERRAIN_FOLLOW',
  targetAltitudeAgl: 80, // 80 metros padrão
  flightSpeedMs: 6.0,
  frontalOverlap: 75, // 75%
  sideOverlap: 65, // 65%
  stripAngle: 0,
  autoAngle: true,
  gridType: 'single',
  corridorWidthM: 60,
  marginBufferM: 10,
  gimbalPitchDeg: -90, // Nadir 90 graus para baixo
  finishAction: 'RTH',
  maxWaypointsPerFile: 200, // Limite DJI App
  photoTriggerMode: 'distance',
  terrainFollowEnabled: true,
  curvedTurns: true
};
